FROM alpine:latest

RUN  	apk update && apk add --no-cache maven
RUN	apk add --no-cache terraform
RUN 	apk add --update --no-cache python make gcc g++ nodejs npm py-pip && \
	pip install databricks-cli && \	
	apk add --update --no-cache openssl jq bash curl && \
	pip install azure-cli && \
	apk del py-pip && \ 
	npm install angular-cli && apk add --no-cache python3 && \
	apk del make gcc g++ nodejs npm 
 
